// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SWZWnQqfWyrfq4uEVRGjNjJldxWS9q8',
    appId: '1:749483708211:web:4257c24b73c57847ce7846',
    messagingSenderId: '749483708211',
    projectId: 'flutter-app-tema3-7d2ea',
    authDomain: 'flutter-app-tema3-7d2ea.firebaseapp.com',
    storageBucket: 'flutter-app-tema3-7d2ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeZMJB2TVMl7Ur9D4eh4Uf8WpNX_dA9d8',
    appId: '1:749483708211:android:c6b16eed34cd9181ce7846',
    messagingSenderId: '749483708211',
    projectId: 'flutter-app-tema3-7d2ea',
    storageBucket: 'flutter-app-tema3-7d2ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjiBEftgdQdmfUm0WVyHCY9LAM2jOIfCA',
    appId: '1:749483708211:ios:aa384c73b4d52af8ce7846',
    messagingSenderId: '749483708211',
    projectId: 'flutter-app-tema3-7d2ea',
    storageBucket: 'flutter-app-tema3-7d2ea.firebasestorage.app',
    iosBundleId: 'com.example.firebaseconnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjiBEftgdQdmfUm0WVyHCY9LAM2jOIfCA',
    appId: '1:749483708211:ios:aa384c73b4d52af8ce7846',
    messagingSenderId: '749483708211',
    projectId: 'flutter-app-tema3-7d2ea',
    storageBucket: 'flutter-app-tema3-7d2ea.firebasestorage.app',
    iosBundleId: 'com.example.firebaseconnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2SWZWnQqfWyrfq4uEVRGjNjJldxWS9q8',
    appId: '1:749483708211:web:bea071edb8136b96ce7846',
    messagingSenderId: '749483708211',
    projectId: 'flutter-app-tema3-7d2ea',
    authDomain: 'flutter-app-tema3-7d2ea.firebaseapp.com',
    storageBucket: 'flutter-app-tema3-7d2ea.firebasestorage.app',
  );
}
